In [9]:
from alpaca.data.historical import CryptoHistoricalDataClient
from alpaca.data.requests import CryptoBarsRequest
from alpaca.data.timeframe import TimeFrame
import datetime

# No keys required for crypto data
client = CryptoHistoricalDataClient()

In [29]:

# Creating request object
request_params = CryptoBarsRequest(
                        symbol_or_symbols=["BTC/USD", "ETH/USD"],
                        timeframe=TimeFrame.Minute,
                        start=datetime.datetime(2022,9,1),
                        end=datetime.datetime(2022,9,7)
                        )
# Retrieve daily bars for Bitcoin in a DataFrame and printing it
btc_bars = client.get_crypto_bars(request_params)

# Convert to dataframe
original_df = btc_bars.df

In [30]:
df

                                      open     high      low    close  \
symbol  timestamp
BTC/USD 2022-09-01 00:00:00+00:00  20049.0  20050.0  20032.0  20032.0
        2022-09-01 00:01:00+00:00  20023.0  20033.0  20004.0  20033.0
        2022-09-01 00:02:00+00:00  20031.0  20068.0  20019.0  20068.0
        2022-09-01 00:03:00+00:00  20071.0  20102.0  20071.0  20102.0
        2022-09-01 00:04:00+00:00  20104.0  20110.0  20086.0  20110.0
...                                    ...      ...      ...      ...
ETH/USD 2022-09-06 23:56:00+00:00   1560.1   1560.5   1557.0   1557.0
        2022-09-06 23:57:00+00:00   1559.1   1560.4   1558.1   1560.2
        2022-09-06 23:58:00+00:00   1560.5   1560.5   1557.5   1557.5
        2022-09-06 23:59:00+00:00   1557.6   1557.9   1557.2   1557.6
        2022-09-07 00:00:00+00:00   1558.8   1560.2   1556.4   1556.8

                                     volume  trade_count          vwap
symbol  timestamp
BTC/USD 2022-09-01 00:00:00+00:00    0.6758         14.0  20040.281296
        2022-09-01 00:01:00+00:00    0.5283         16.0  20014.767367
        2022-09-01 00:02:00+00:00    2.0242         32.0  20037.934542
        2022-09-01 00:03:00+00:00    5.2678         26.0  20099.925244
        2022-09-01 00:04:00+00:00    0.0324         10.0  20092.108025
...                                     ...          ...           ...
ETH/USD 2022-09-06 23:56:00+00:00   22.0630         33.0   1557.747441
        2022-09-06 23:57:00+00:00   14.9080         17.0   1559.732774
        2022-09-06 23:58:00+00:00   14.9060         24.0   1559.707782
        2022-09-06 23:59:00+00:00   42.7250         30.0   1557.378834
        2022-09-07 00:00:00+00:00  413.1430         73.0   1557.769166

[17243 rows x 7 columns]

In [31]:
df = original_df.loc["BTC/USD"]

In [32]:
df.pct_change()

,open,high,low,close,volume,trade_count,vwap
timestamp,,,,,,,
2022-09-01 00:00:00+00:00,20049.0,20050.0,20032.0,20032.0,0.6758,14.0,20040.281296
2022-09-01 00:01:00+00:00,20023.0,20033.0,20004.0,20033.0,0.5283,16.0,20014.767367
2022-09-01 00:02:00+00:00,20031.0,20068.0,20019.0,20068.0,2.0242,32.0,20037.934542
2022-09-01 00:03:00+00:00,20071.0,20102.0,20071.0,20102.0,5.2678,26.0,20099.925244
2022-09-01 00:04:00+00:00,20104.0,20110.0,20086.0,20110.0,0.0324,10.0,20092.108025
...,...,...,...,...,...,...,...
2022-09-06 23:56:00+00:00,18810.0,18813.0,18794.0,18794.0,11.2416,28.0,18800.144597
2022-09-06 23:57:00+00:00,18799.0,18807.0,18795.0,18807.0,0.8328,6.0,18802.189241
2022-09-06 23:58:00+00:00,18811.0,18811.0,18800.0,18800.0,0.0005,3.0,18804.400000
2022-09-06 23:59:00+00:00,18801.0,18801.0,18782.0,18791.0,10.9349,25.0,18785.913241
2022-09-07 00:00:00+00:00,18789.0,18804.0,18763.0,18764.0,6.5805,38.0,18786.329701